# GitHub Actions for GEOS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>
# Based on AZP configuration by Mateusz Loskot <mateusz at loskot dot net>
#

name: CI
on: [push, pull_request]

env:
  BUILD_TYPE: 'Release'
  MAKEFLAGS: '-j2'

jobs:
  linux:
    name: 'Linux'
    strategy:
      matrix:
        ci:
        - {
          compiler: g++,
          build: autotools,
          cxxstd: 11,
          arch: 64,
          packages: 'g++ automake doxygen git2cl',
          os: ubuntu-latest
        }
#        - {
#          compiler: g++,
#          build: autotools,
#          cxxstd: 11,
#          arch: 32,
#          packages: 'g++-4.8-multilib gcc-4.8-multilib g++-multilib gcc-multilib doxygen automake git2cl',
#          os: ubuntu-18.04
#        }


    runs-on: ${{ matrix.ci.os }}
    steps:

    - name: 'Install'
      run: |
        set -e
        uname -a
        sudo -E apt-get update
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install make ${{ matrix.ci.packages }}

    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Build'
      run: |
        set -e
        ./autogen.sh
        mkdir build.autotools
        cd build.autotools
        export CFLAGS="-std=c++${{ matrix.ci.cxxstd }} -m${{ matrix.ci.arch }}"
        ../configure CC=${{ matrix.ci.compiler }} CXX=${{ matrix.ci.compiler }} CXXFLAGS="$CFLAGS" CFLAGS="$CFLAGS"
        make && make check && make distcheck



